<?php

namespace WebSite\BackEndBundle\Entity;

/**
 * ImageSliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSliderRepository extends \Doctrine\ORM\EntityRepository
{    
    
    public function findCurrentImage()
    {
        $qb = $this->createQueryBuilder('i');
        $qb->where('i.dateFin >= :datenow')
            ->orderBy('i.dateCreation','DESC')
            ->setParameter('datenow', (new \DateTime()));
        
        return $qb->getQuery()->getResult();
    }
}
