<?php

namespace WebSite\BackEndBundle\Entity;

/**
 * LogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTrusts()
    {
        return $this->findBy(array('type'=>1));
    }
    
    public function getPartners()
    {
        return $this->findBy(array('type'=>2));
    }
}
