<?php

namespace WebSite\BackEndBundle\Entity;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Permet de trouver toutes les news créées depuis 1 mois
     * @return type une liste de news
     */
    public function findNews()
    {        
        $qb = $this->createQueryBuilder('n');
        $qb->where('n.published = :published')
            ->andWhere("n.dateCreation >= :dateCreation")
            ->orderBy('n.dateCreation','DESC')
            ->setParameter('published', true)
            ->setParameter('dateCreation', (new \DateTime("- 4 weeks")));
        
        return $qb->getQuery()->getResult();
    }
    
    /**
     * Permet de rechercher des news selon un mot clé dans son titre et/ou description
     * @param type $search un mot clé de type texte
     * @return type une liste de news
     */
    public function getSearch($search)
    {
        $qb=$this->createQueryBuilder("n");
         return $qb->where( $qb->expr()->like('n.title', ':title'))
            ->orWhere($qb->expr()->like('n.description', ':description'))
            ->andWhere('n.published = :published')
             ->setParameter('title','%'.$search.'%')
             ->setParameter('description','%'.$search.'%')
             ->setParameter('published',1)
             ->getQuery()
             ->getResult();
    }
}
