<?php

namespace Application\UserBundle\Entity;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends \Doctrine\ORM\EntityRepository {

    public function orderByName() {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
                ->from('Application\UserBundle\Entity\Contract', 'c')
                ->orderBy('c.name', 'ASC')
        ;
        return $qb;
    }
//
//    /**
//     * Find all id
//     * @return type
//     */
//    public function findAllById($companiesId) {
//        if($companiesId==null){
//            $companiesId=array();
//            $companiesId[]=0;
//        }
//        $qb = $this->_em->createQueryBuilder();
//        $qb->select('c')
//                ->from('Intranet\EntrepriseBundle\Entity\Company', 'c')
//                ->where($qb->expr()->in('c.id', $companiesId))
//                ->orderBy('c.name')
//                ;
//        return $qb->getQuery()->getResult();
//    }
//    
//    /**
//     * Find all by user 
//     * @return type
//     */
//    public function findAllByUsers($entities) {
//        $ids=array();
//        foreach ($entities as $entity){
//            $ids[]=$entity->getId();
//        }
//        if(count($ids)==0){
//            $ids[]=0;
//        }
//        $qb = $this->_em->createQueryBuilder();
//        $qb->select('c')
//                ->from('Intranet\EntrepriseBundle\Entity\Company', 'c')
//                ->join("c.projects", "p")
//                ->join("p.tasks", "t")
//                ->join("t.events", "e")
//                ->join("e.timereport", "tr")
//                ->join("tr.user", "u")
//                ->where($qb->expr()->in('u.id', $ids))
//                ->orderBy('c.name')
//                ;
//        return $qb->getQuery()->getResult();
//    }
//    
//    /**
//     * Find all by user id
//     * @return type
//     */
//    public function findAllByUsersId($ids) {
//        if($ids==null){
//            $ids=array();
//            $ids[]=0;
//        }
//        $qb = $this->_em->createQueryBuilder();
//        $qb->select('c')
//                ->from('Intranet\EntrepriseBundle\Entity\Company', 'c')
//                ->join("c.projects", "p")
//                ->join("p.tasks", "t")
//                ->join("t.events", "e")
//                ->join("e.timereport", "tr")
//                ->join("tr.user", "u")
//                ->where($qb->expr()->in('u.id', $ids))
//                ->orderBy('t.name')
//                ;
//        return $qb->getQuery()->getResult();
//    }

}
