<?php

namespace Intranet\CalendarBundle\Entity;
use Application\UserBundle\Entity\User;

/**
 * TimeReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeReportRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find the current timereport to the user
     * @param type $user
     * @return type
     */
    public function findCurrentCRT($user)
    {
        $qb = $this->createQueryBuilder('crt');
        $qb->where('crt.user = :user')
            ->andWhere('YEAR(crt.date ) = :year')
            ->andWhere('MONTH(crt.date ) = :month')
                ->setParameter('year', date('Y'))
                ->setParameter('month', date('m'))
                ->setParameter('user', $user);
        
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    /**
     * Find timereport to a user by month and year
     * @param type $user
     * @param type $month
     * @param type $year
     * @return type
     */
    public function findCRT($user,$month,$year)
    {
        $qb = $this->createQueryBuilder('crt');
        $qb->where('crt.user = :user')
            ->andWhere('YEAR(crt.date ) = :year')
            ->andWhere('MONTH(crt.date ) = :month')
                ->setParameter('year', $year)
                ->setParameter('month', $month)
                ->setParameter('user', $user);
        
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    /**
     * Find timereport to a user by month and year
     * @param type $user
     * @param type $month
     * @param type $year
     * @return type
     */
    public function findCRTForAYear($user,$year)
    {
        $yearp1=$year+1;
        $qb = $this->createQueryBuilder('crt');
        $qb->where('crt.user = :user')
            ->andWhere($qb->expr()->orX(
                    $qb->expr()->andX(
                            $qb->expr()->eq('YEAR(crt.date )', $year),
                            $qb->expr()->gt('MONTH(crt.date )', '5')
                            ),
                    $qb->expr()->andX(
                            $qb->expr()->eq('YEAR(crt.date )', $yearp1),
                            $qb->expr()->lte('MONTH(crt.date )', '5')
                            )
                    )
                 
            )
             ->setParameter('user', $user)
                ;
        
        return $qb->getQuery()->getResult();
    }
    
   
}
