<?php

namespace Intranet\CVBundle\Entity;

/**
 * CategoryActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
