<?php

namespace Intranet\CVBundle\Entity;

/**
 * CategorySkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorySkillRepository extends \Doctrine\ORM\EntityRepository
{
}
