<?php

namespace Intranet\CVBundle\Entity;

/**
 * LanguageProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
