<?php

namespace Intranet\CVBundle\Entity;

/**
 * LevelLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
