<?php

namespace Intranet\CVBundle\Entity;

/**
 * LevelStudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelStudyRepository extends \Doctrine\ORM\EntityRepository
{
}
