<?php

namespace Intranet\CVBundle\Entity;

/**
 * PersonnalProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnalProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
