<?php

namespace Intranet\CVBundle\Entity;

/**
 * ProfessionalFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalFunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
