<?php

namespace Intranet\CVBundle\Entity;

/**
 * ProposedAppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposedAppointmentRepository extends \Doctrine\ORM\EntityRepository
{
}
