<?php

namespace Intranet\CVBundle\Entity;

/**
 * SkillTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillTagRepository extends \Doctrine\ORM\EntityRepository
{
}
