<?php

namespace Intranet\CVBundle\Entity;

/**
 * StudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyRepository extends \Doctrine\ORM\EntityRepository
{
}
